ARG DOCKER_REGISTRY
ARG CTR_REGISTRY
ARG CTR_TAG

FROM $CTR_REGISTRY/osm-edge-interceptor:compiler.$CTR_TAG as compiler

FROM $DOCKER_REGISTRY/ubuntu:$CTR_TAG

COPY --from=compiler /usr/local/sbin/bpftool /usr/local/sbin/bpftool

RUN apt-get update && apt-get install -y libelf-dev make sudo clang iproute2 ethtool tcpdump vim