name: ImageScan
on:
  push:
    branches:
      - main

jobs:
  imagescan:
    name: Scan images for security vulnerabilities
    runs-on: ubuntu-latest
    env:
      CTR_REGISTRY: "localhost:5000"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker images
        env:
          DOCKER_BUILDX_OUTPUT: type=docker
        run: make docker-build-cross-osm
      #- name: Setup Trivy
      #  run: make trivy-ci-setup
      #- name: Scan docker images for vulnerabilities
      #  run: make trivy-scan-images