name: ImageScan
on:
  push:
    branches:
      - main

jobs:
  ubuntuimagescan:
    name: Scan Ubuntu images for security vulnerabilities
    runs-on: ubuntu-latest
    env:
      CTR_REGISTRY: ${{ secrets.RELEASE_REGISTRY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker images
        env:
          DOCKER_BUILDX_OUTPUT: type=docker
        run: make docker-build
      - name: Setup Trivy
        run: make trivy-ci-setup
      - name: Scan docker images for vulnerabilities
        run: make trivy-scan-images